name: Build ZMK Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shield: [hxlit]

    steps:
      - name: Checkout ZMK Config
        uses: actions/checkout@v4

      - name: Initialize the repository
        run: |
          pip install west
          west init -l config
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app -d build             -b adafruit_feather_nrf52840             -- -DSHIELD=${{ matrix.shield }}

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware-${{ matrix.shield }}
          path: build/zephyr/zmk.uf2
